language: python
sudo: false
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
    - pypy
    - pypy3
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
  - COVERAGE_PROCESS_START=.coveragerc coverage run -m zope.testrunner --test-path=src -vv
after_success:
  - coverage combine
  - coveralls
notifications:
    email: false
cache: pip
